In [1]:
import numpy as np
from array import array

In [2]:
lista = [i for i in range(5)]
a = array('i', lista)
a

array('i', [0, 1, 2, 3, 4])

In [3]:
a*2

array('i', [0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [4]:
vetor = np.array(lista)
vetor

array([0, 1, 2, 3, 4])

In [5]:
vetor *2

array([0, 2, 4, 6, 8])

In [6]:
matriz = np.array([[[1, 5 , 3],[4,5,6]],[[1, 58 , 3],[4,59,67]]])
print(matriz)
matriz.shape

[[[ 1  5  3]
  [ 4  5  6]]

 [[ 1 58  3]
  [ 4 59 67]]]


(2, 2, 3)

In [7]:
arr = np.array([1, 5 , 3])
print(arr.dtype)
arr

int32


array([1, 5, 3])

In [8]:
arr_2 = np.full((5,2), 10)
arr_2

array([[10, 10],
       [10, 10],
       [10, 10],
       [10, 10],
       [10, 10]])

In [9]:
arr_3 = np.random.rand(4,2,3)
arr_3

array([[[0.64738593, 0.53977404, 0.83988728],
        [0.87791691, 0.73010667, 0.29069817]],

       [[0.59621943, 0.11416953, 0.61989612],
        [0.48512437, 0.82099585, 0.30122329]],

       [[0.36794758, 0.25733312, 0.09501564],
        [0.14877777, 0.32353346, 0.53120309]],

       [[0.49026841, 0.2456858 , 0.57543306],
        [0.69885565, 0.46776004, 0.3633754 ]]])

In [10]:
arr= np.random.randint(5,20, size = (3,3))
arr

array([[ 5,  6, 11],
       [14, 12, 16],
       [13, 12, 19]])

In [12]:
arr[1,1]

12

In [13]:
arr[0:2, :]

array([[ 5,  6, 11],
       [14, 12, 16]])

In [14]:
arr= np.random.randint(5,20, size = (3,3))
arr

array([[18, 18, 16],
       [13, 13, 16],
       [ 8,  5, 10]])

In [15]:
arr.std()

4.2946995755750415

In [16]:
import pandas as pd

In [17]:
df = pd.DataFrame(arr, columns=['a', 'b', 'c'])
df ['idade'] = [10, 20, 30]
df

a   b   c  idade
0  18  18  16     10
1  13  13  16     20
2   8   5  10     30

In [18]:
from datetime import datetime, timedelta

In [20]:
x = datetime.today()
y = x + timedelta(days = 1)

In [21]:
df1 = pd.DataFrame({'Nome': ['Jo', 'Ma'], 'Idade':[20, 50]}, index = [x,y])
df1

Nome  Idade
2024-01-29 21:23:14.604490   Jo     20
2024-01-30 21:23:14.604490   Ma     50

In [22]:
arr = (np.random.rand(10) *10).astype(int)
arr

array([0, 7, 5, 8, 8, 0, 4, 1, 3, 9])

In [23]:
arr1 = np.random.randint(0,10, (3,3))
arr1

array([[5, 3, 0],
       [9, 6, 3],
       [3, 8, 0]])

In [24]:
arr1[1,:]= -1
arr1

array([[ 5,  3,  0],
       [-1, -1, -1],
       [ 3,  8,  0]])